services:
  - name: "My Pages"
    endpoints:
      - url: "http://dkjdkj.tttttttttt.top"
      - url: "http://qweasdzxc.tttttttttt.top"
      - url: "http://aoei.tttttttttt.top"
      - url: "http://wdzzzyx.tttttttttt.top"
  - name: "My Services"
    endpoints:
      - url: "https://2024.ch3nyang.top/health"
      - url: "https://2024.ch3nyang.top"

notifications:
  enabled: false
